version: 0.3.{build}
 
environment:
  semver: '0.0.0'

platform: Any CPU
configuration: Release

pull_requests:
  do_not_increment_build_number: true

init:
- ps: |
      $env:semver = ${env:APPVEYOR_BUILD_VERSION}
      $env:semver = $env:semver.Substring(0, [System.Math]::Min(20, $semver.Length))
      echo %$env:semver%

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{semver}'
  assembly_file_version: '{semver}'
  assembly_informational_version: '{semver}'

artifacts:
  - path: '**\Bridge.AWS*.nupkg'

before_build:
  - cmd: nuget restore src/Bridge.AWS.sln
  
build:
  project: src/Bridge.AWS.sln
  verbosity: normal
  publish_nuget: true

deploy:
  provider: NuGet
  api_key:
    secure: WrL2uPCxsKi6WaC+BqV9F6NzgFqtc8P9rtTOrTmcNtVg8YMbbniVxWglwGau0byD
  skip_symbols: true
  artifact: /.*\.nupkg/