version: 0.3.{build}
 
pull_requests:
  do_not_increment_build_number: true

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
  - cmd: nuget restore src/Bridge.AWS.sln
  
build:
  project: src/Bridge.AWS.sln
  verbosity: normal
  publish_nuget: false
 
after_build:
  - ps: "Write-Host \"Setting .nuspec version tag to {version}\"\n\n$content = (Get-Content src/Bridge.AWS.nuspec) \n$content = $content -replace '\\$version\\$',{version}\n\n$content | Out-File src/Bridge.AWS.nuspec\n\nnuget pack src/Bridge.AWS.csproj"

deploy:
  provider: NuGet
  api_key:
    secure: WrL2uPCxsKi6WaC+BqV9F6NzgFqtc8P9rtTOrTmcNtVg8YMbbniVxWglwGau0byD
  skip_symbols: true
  artifact: /.*\.nupkg/