version: 0.3.{build}
 
pull_requests:
  do_not_increment_build_number: true

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
  - cmd: nuget restore src/Bridge.AWS.sln
  
build:
  project: src/Bridge.AWS.sln
  verbosity: normal
  publish_nuget: false
 
after_build:
  - cmd: nuget pack src/Bridge.AWS.csproj -version {APPVEYOR_BUILD_VERSION}

deploy:
  provider: NuGet
  api_key:
    secure: WrL2uPCxsKi6WaC+BqV9F6NzgFqtc8P9rtTOrTmcNtVg8YMbbniVxWglwGau0byD
  skip_symbols: true
  artifact: /.*\.nupkg/